# Generated by Django 2.2.17 on 2020-12-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, default='', verbose_name='プロフィール'),
        ),
    ]
